line-length = 80
target-version = "py311"

[lint]
# https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
select = ["E", "F", "UP", "B", "SIM", "I", "W", "N", "D", "ASYNC", "A", "COM", "CPY", "C4", "ISC", "EXE", "LOG", "G", "PIE", "PYI", "PT", "Q", "SLF", "PTH", "ARG", "INT", "TD", "NPY"]